version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container-skinme
    environment:
      MYSQL_ROOT_PASSWORD: veha0508
      MYSQL_DATABASE: skinme_laravel
      MYSQL_USER: admin
      MYSQL_PASSWORD: veha0508
    ports:
      - "3308:3306" 
    volumes:
      - ./mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container-skinme
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql
